version: '3'
services:
  db:
    build: .
    container_name: mysql-sample
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306